version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "messages_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"